# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc919912f1a6bc2b9d4aef627c2f31bcd4479d9eae29200088cf4b84bf9783f7e71b8f27ff99ceb602693dd7956cfe07df10808bc85f36b9a3519cc479b28b8

test:
  secret_key_base: 99028fbd7ee839605d9e8d3a5098564892f672185f0cf9e11b1bfbaa9b2f6731b572a2f784c69d73fa64ce0d4d988381990418d5c2953b6c316e83eb68504200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
